name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['6.0']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

      - name: Start test server
        run: npm run start:test &

      - name: Run all Cypress tests on Chrome
        id: cypress-chrome
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: npm start

      - name: Run all Cypress tests on Edge
        id: cypress-edge
        uses: cypress-io/github-action@v5
        with:
          browser: edge
          start: npm start


  deploy:
    needs: build-and-test
    if: needs.build-and-test.result == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        env:
          KEY: ${{ secrets.RENDER_KEY }}
        run: |
          curl -X GET -sS $KEY
